name: dolphin_livin_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.4.0
  webview_flutter: ^4.9.0
  flutter_screenutil: ^5.9.3
  webview_flutter_android: ^3.16.7
  webview_flutter_wkwebview: ^3.15.0
  flutter_launcher_icons: ^0.13.1
  go_router: ^14.2.8
  url_launcher: ^6.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/ic_livin.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
