name: dolphin_livin_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+23

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.4.0
  webview_flutter: ^4.9.0
  flutter_screenutil: ^5.9.3
  webview_flutter_android: ^3.16.7
  webview_flutter_wkwebview: ^3.15.0
  flutter_launcher_icons: ^0.13.1
  go_router: ^14.2.8
  url_launcher: ^6.3.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  dio: ^5.7.0
  crypto: ^3.0.6
  shimmer: ^3.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  fluttertoast: ^8.2.8
  flutter_markdown: ^0.7.4+1
  http: ^1.2.2
  permission_handler: ^11.3.1
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/transfer/
    - google_fonts/

flutter_launcher_icons:
  image_path: "assets/images/ic_livin.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
